### ISSUE TITLE
로그인을 할 경우, 로비페이지로 이동하며, 로그아웃할 수 있어야 한다. 또한, 토큰이 있을 경우 바로 로비페이지로 이동한다. 로그인 외 페이지 전체가 회원 인증이 필요하기 때문이다.

### ISSUE THREAD

**Issue by letsjo** [Green-5team/CodeLearn-Frontend#8]
## TODO
- [x] 로그인 페이지 그리기
- [x] 토큰이 있을 경우, 로비 페이지로 바로 redirect 하기
- [x] 토큰이 없을 경우, 로그인 페이지로 들어가기
- [x] 로비페이지에서 [종료] 만들고, 로그아웃 확인 alert 만들기 ( 추후, SweetAlert 으로 변경할 예정 )
